// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using POST.DAL;

#nullable disable

namespace POST.DAL.Migrations
{
    [DbContext(typeof(PostDbContext))]
    [Migration("20250329160259_M5")]
    partial class M5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("POST.Core.Abstractions.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Destinations");

                    b.HasDiscriminator<string>("DestinationType").HasValue("Destination");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("POST.Core.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("POST.Core.Models.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("Box");
                });

            modelBuilder.Entity("POST.Core.Models.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentSenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentSenderId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("POST.Core.Models.Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParcelLockerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcelLockerId");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("POST.Core.Models.Department", b =>
                {
                    b.HasBaseType("POST.Core.Abstractions.Destination");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Department");
                });

            modelBuilder.Entity("POST.Core.Models.ParcelLocker", b =>
                {
                    b.HasBaseType("POST.Core.Abstractions.Destination");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("ParcelLocker");
                });

            modelBuilder.Entity("Post.Core.Models.HomeDelivery", b =>
                {
                    b.HasBaseType("POST.Core.Abstractions.Destination");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("HomeDelivery");
                });

            modelBuilder.Entity("POST.Core.Abstractions.Destination", b =>
                {
                    b.HasOne("POST.Core.Models.Address", "Address")
                        .WithMany("Destinations")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("POST.Core.Models.Box", b =>
                {
                    b.HasOne("POST.Core.Models.Shipment", "Shipment")
                        .WithMany("Boxes")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("POST.Core.Models.Shipment", b =>
                {
                    b.HasOne("POST.Core.Models.Department", "DepartmentSender")
                        .WithMany("SentShipments")
                        .HasForeignKey("DepartmentSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POST.Core.Abstractions.Destination", "Destination")
                        .WithMany("ExceptedShipments")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepartmentSender");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("POST.Core.Models.Slot", b =>
                {
                    b.HasOne("POST.Core.Models.ParcelLocker", "ParcelLocker")
                        .WithMany("Slots")
                        .HasForeignKey("ParcelLockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelLocker");
                });

            modelBuilder.Entity("POST.Core.Abstractions.Destination", b =>
                {
                    b.Navigation("ExceptedShipments");
                });

            modelBuilder.Entity("POST.Core.Models.Address", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("POST.Core.Models.Shipment", b =>
                {
                    b.Navigation("Boxes");
                });

            modelBuilder.Entity("POST.Core.Models.Department", b =>
                {
                    b.Navigation("SentShipments");
                });

            modelBuilder.Entity("POST.Core.Models.ParcelLocker", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
